### ISSUE TITLE
"PAGE" script returns a black image for GPU and a different output from CPU

### ISSUE THREAD

**Issue by lorenzob** [JalaliLabUCLA/phycv#11]
Hi, I'm running the run_page.py on the attached images (with the original parameters).

With ring.jpg I get a completely black image from GPU (with original or any parameters). CPU output looks fine.

Downscaling the image, the GPU result is slightly different from the CPU one (and wrong in my opinion). I get a similar result cropping the original image a little bit.

Linux Mint 5.4.0-137-generic
Driver Version: 470.161.03
CUDA Version: 11.7.99
NVIDIA GeForce RTX 2070 with Max-Q Design

[ring](https://user-images.githubusercontent.com/85481/219392430-b11488ef-11ab-4478-bb19-f1a3be777901.jpg)
[smaller](https://user-images.githubusercontent.com/85481/219392437-71155ce4-9774-45dd-bea1-20b853133760.jpg)
[smallest](https://user-images.githubusercontent.com/85481/219392440-ba2eda6f-bd12-4b86-ade8-c520ac06d4a6.jpg)

Output on the "smaller" image (the image background is completely uniform):

CPU:

![PAGE_CPU_demo](https://user-images.githubusercontent.com/85481/219394420-60f3f8eb-18af-46e9-b855-8c885b207d10.jpg)

GPU:

![PAGE_GPU_demo](https://user-images.githubusercontent.com/85481/219394445-677bd7d7-0528-4a9b-a98e-fa2edbe2ecec.jpg)

**Comment by JalaliLabUCLA** [comment]
Hi,
Thanks for reporting the issue. I did some initial investigation and looks like it is because the numerical precision in the CPU (float64) and GPU (float32) versions are different. Currently you can set the frequency grid variables `u` and `v` in the `init_kernel()` function of `PAGE_GPU.py` to `double()` and it will mitigate this issue. I will work on a PR that improves this.

**Comment by JalaliLabUCLA** [comment]
updated in #13
